
const sampleData = [
  {
    id: 1,
    username: "cryptoqueen",
    fullName: "Alina Petrovna",
    country: "UAE",
    docType: "Passport",
    idNumber: "****1234",
    source: "Manual",
    submittedOn: "30 July 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Pending",
  },
  {
    id: 2,
    username: "investhunter",
    fullName: "Annette Black",
    country: "Japan",
    docType: "Driver’s License",
    idNumber: "****X45",
    source: "Auto",
    submittedOn: "01 Aug 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Auto-Approved",
  },
  {
    id: 3,
    username: "angelvision",
    fullName: "Ronald Richards",
    country: "USA",
    docType: "Emirates ID",
    idNumber: "****542",
    source: "Manual",
    submittedOn: "01 Aug 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Rejected",
  },
  {
    id: 4,
    username: "dealMaker22",
    fullName: "Eleanor Pena",
    country: "Switzerland",
    docType: "Driver’s License",
    idNumber: "****4824",
    source: "Manual",
    submittedOn: "01 Aug 2025",
    reviewedBy: "-",
    status: "Resubmitted",
  },
  {
    id: 5,
    username: "capshunter",
    fullName: "Leslie Alexander",
    country: "Australia",
    docType: "Driver’s License",
    idNumber: "****4445",
    source: "Manual",
    submittedOn: "01 Aug 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Pending",
  },
  {
    id: 6,
    username: "angelpromoter",
    fullName: "Albert Flores",
    country: "UK",
    docType: "Emirates ID",
    idNumber: "****Y445",
    source: "Auto",
    submittedOn: "01 Aug 2025",
    reviewedBy: "Thomas (Staff Admin) thomas@gmail.com",
    status: "Auto-Approved",
  },
  {
    id: 7,
    username: "wealthtrack",
    fullName: "Ralph Edwards",
    country: "India",
    docType: "Passport",
    idNumber: "****9934",
    source: "Auto",
    submittedOn: "01 Aug 2025",
    reviewedBy: "-",
    status: "Pending",
  },
  {
    id: 8,
    username: "investicoin",
    fullName: "Jerome Bell",
    country: "China",
    docType: "Driver’s License",
    idNumber: "****X45",
    source: "Auto",
    submittedOn: "01 Aug 2025",
    reviewedBy: "-",
    status: "API Failed",
  },
  {
    id: 9,
    username: "fundnexus",
    fullName: "Marvin McKinney",
    country: "Canada",
    docType: "Passport",
    idNumber: "****2211",
    source: "Manual",
    submittedOn: "01 Aug 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Auto-Approved",
  },
  {
    id: 10,
    username: "refeking",
    fullName: "Cameron Williamson",
    country: "India",
    docType: "Driver’s License",
    idNumber: "****Y445",
    source: "Manual",
    submittedOn: "01 Aug 2025",
    reviewedBy: "Lovekush (IT) lovekush@gmail.com",
    status: "Rejected",
  },
    {
    id: 1,
    username: "cryptoqueen",
    fullName: "Alina Petrovna",
    country: "UAE",
    docType: "Passport",
    idNumber: "****1234",
    source: "Manual",
    submittedOn: "30 July 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Pending",
  },
  {
    id: 2,
    username: "investhunter",
    fullName: "Annette Black",
    country: "Japan",
    docType: "Driver’s License",
    idNumber: "****X45",
    source: "Auto",
    submittedOn: "01 Aug 2025",
    reviewedBy: "John (Staff Admin) john@gmail.com",
    status: "Auto-Approved",
  },
];

export default sampleData;
